# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-09 13:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(default='', upload_to='avatar/%Y/%m', verbose_name='头像'),
        ),
    ]
