# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-15 21:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20190309_1359'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailverifyrecord',
            name='send_type',
        ),
    ]
