# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-25 09:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20190525_0930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(default='group1\\M00/00/00/rBAABVzok7aAbcZnAAAUSzOR5oA8666191', upload_to='avatar/%Y/%m', verbose_name='头像'),
        ),
    ]
