# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-04 17:59
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Music',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('music_name', models.CharField(max_length=32, verbose_name='音乐名')),
                ('image', models.ImageField(default='', upload_to='music/%Y/%m', verbose_name='封面')),
                ('fav_nums', models.IntegerField(default=0, verbose_name='收藏数')),
                ('click_nums', models.IntegerField(default=0, verbose_name='点击数')),
                ('music_time', models.CharField(max_length=10, verbose_name='时长')),
                ('isHot', models.BooleanField(default=False, verbose_name='是否热门')),
                ('music_language', models.CharField(default='中文', max_length=20, verbose_name='语种')),
                ('release_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='发布时间')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '音乐',
                'verbose_name_plural': '音乐',
            },
        ),
        migrations.CreateModel(
            name='MusicType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(max_length=20, verbose_name='音乐类型')),
            ],
            options={
                'verbose_name': '音乐类型',
                'verbose_name_plural': '音乐类型',
            },
        ),
        migrations.CreateModel(
            name='Singer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=24, verbose_name='歌手名称')),
                ('gender', models.CharField(choices=[('male', '男'), ('female', '女')], default='female', max_length=6, verbose_name='性别')),
                ('points', models.CharField(max_length=100, verbose_name='歌手简述')),
                ('national', models.CharField(default='中国', max_length=20, verbose_name='国籍')),
                ('isHot', models.BooleanField(default=False, verbose_name='是否热门')),
                ('avatar', models.ImageField(default='', max_length=200, upload_to='singer/%Y/%m', verbose_name='头像')),
                ('fav_nums', models.IntegerField(default=0, verbose_name='收藏数')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '歌手',
                'verbose_name_plural': '歌手',
            },
        ),
        migrations.AddField(
            model_name='music',
            name='music_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='music.MusicType', verbose_name='音乐类型'),
        ),
    ]
