# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-04 20:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='music',
            name='music_file',
            field=models.FileField(default='', upload_to='song/%Y/%m', verbose_name='音乐文件'),
        ),
    ]
