# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-05 11:59
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_music_music_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_name', models.CharField(max_length=32, verbose_name='视频名')),
                ('image', models.ImageField(default='', upload_to='video/%Y/%m', verbose_name='视频封面')),
                ('video_file', models.FileField(upload_to='video/src/%Y/%m', verbose_name='视频文件')),
                ('desc', models.CharField(max_length=300, verbose_name='视频描述描述')),
                ('fav_nums', models.IntegerField(default=0, verbose_name='收藏数')),
                ('click_nums', models.IntegerField(default=0, verbose_name='点击数')),
                ('comment_nums', models.IntegerField(default=0, verbose_name='评论数')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '视频',
                'verbose_name_plural': '视频',
            },
        ),
        migrations.RenameField(
            model_name='singer',
            old_name='points',
            new_name='desc',
        ),
    ]
