# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-10 14:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0004_music_singer'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='singer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='music.Singer', verbose_name='作者'),
        ),
    ]
