# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-10 21:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0005_video_singer'),
    ]

    operations = [
        migrations.AddField(
            model_name='music',
            name='isNew',
            field=models.BooleanField(default=False, verbose_name='是否新歌'),
        ),
    ]
