# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-11 19:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0007_video_isrecommend'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='video_time',
            field=models.CharField(default='', max_length=10, verbose_name='时长'),
        ),
        migrations.AlterField(
            model_name='music',
            name='music_time',
            field=models.CharField(default='', max_length=10, verbose_name='时长'),
        ),
    ]
