# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-14 11:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0008_auto_20190311_1955'),
    ]

    operations = [
        migrations.AddField(
            model_name='music',
            name='comment_nums',
            field=models.IntegerField(default=0, verbose_name='评论数'),
        ),
    ]
