# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-18 09:32
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0009_music_comment_nums'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='新闻标题')),
                ('image', models.ImageField(upload_to='news/%Y/%m', verbose_name='封面图')),
                ('content', models.CharField(max_length=200, verbose_name='内容')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('singer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music.Singer', verbose_name='关联的歌手')),
            ],
            options={
                'verbose_name': '新闻',
                'verbose_name_plural': '新闻',
            },
        ),
    ]
