# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-24 10:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0011_remove_news_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='video_file',
        ),
        migrations.AddField(
            model_name='video',
            name='video_url',
            field=models.URLField(null=True, verbose_name='视频链接'),
        ),
    ]
