# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-24 10:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0012_auto_20190524_1023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='video_url',
            field=models.TextField(null=True, verbose_name='视频链接'),
        ),
    ]
