# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-24 10:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0013_auto_20190524_1031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='image',
            field=models.ImageField(null=True, upload_to='video/%Y/%m', verbose_name='视频封面'),
        ),
        migrations.AlterField(
            model_name='video',
            name='video_url',
            field=models.URLField(null=True, verbose_name='视频链接'),
        ),
    ]
