# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-14 11:48
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('music', '0008_auto_20190311_1955'),
        ('operation', '0005_auto_20190312_1546'),
    ]

    operations = [
        migrations.CreateModel(
            name='MusicComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(default='', verbose_name='评论详情')),
                ('add_time', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('music', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music.Music', verbose_name='评论所属的音乐')),
                ('user', models.ForeignKey(max_length=32, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='评论者')),
            ],
            options={
                'verbose_name': '音乐评论',
                'verbose_name_plural': '音乐评论',
            },
        ),
        migrations.RemoveField(
            model_name='videocomment',
            name='video',
        ),
        migrations.DeleteModel(
            name='VideoComment',
        ),
    ]
