# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-14 18:37
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0009_music_comment_nums'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('operation', '0006_auto_20190314_1148'),
    ]

    operations = [
        migrations.CreateModel(
            name='FavoriteMusic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='评论时间')),
                ('music', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music.Music', verbose_name='音乐')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '音乐收藏',
                'verbose_name_plural': '音乐收藏',
            },
        ),
        migrations.RemoveField(
            model_name='userfavorite',
            name='user',
        ),
        migrations.DeleteModel(
            name='UserFavorite',
        ),
    ]
