# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-14 22:27
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0009_music_comment_nums'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('operation', '0007_auto_20190314_1837'),
    ]

    operations = [
        migrations.CreateModel(
            name='FavoriteVideo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='评论时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music.Video', verbose_name='视频')),
            ],
            options={
                'verbose_name': '视频收藏',
                'verbose_name_plural': '视频收藏',
            },
        ),
    ]
