# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-14 22:30
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0009_music_comment_nums'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('operation', '0008_favoritevideo'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(default='', verbose_name='评论详情')),
                ('add_time', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('user', models.ForeignKey(max_length=32, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='评论者')),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music.Video', verbose_name='评论所属的视频')),
            ],
            options={
                'verbose_name': '视频评论',
                'verbose_name_plural': '视频评论',
            },
        ),
        migrations.AlterField(
            model_name='favoritemusic',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='收藏时间'),
        ),
        migrations.AlterField(
            model_name='favoritevideo',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='收藏时间'),
        ),
    ]
